export const types = {
    IPPON_WHITE: "IPPON_WHITE",
    IPPON_BLUE: "IPPON_BLUE",
    GOLDEN_SCORE: "GOLDEN_SCORE",
    DELETE_GOLDEN: "DELETE_GOLDEN",
    DELETE_IPPON_BLUE: "DELETE_IPPON_BLUE",
    DELETE_IPPON_WHITE: "DELETE_IPPON_WHITE"
}